### ISSUE TITLE
Compilation of CAFE3.1

### ISSUE THREAD

**Issue by DRL** [hahnlab/CAFE#1]
Hi, 

would like to use CAFE3.1 but am having trouble compiling it under Ubuntu. 

it compiles under macosx, though...

thanks in advance,

[commands.txt](https://github.com/hahnlab/CAFE/files/575420/cafe_errors.txt)

dom

**Comment by hahnlab** [comment]
Hi Dom,

In the cafe Makefile, move the $(LINKS) option to the end of the line. So line 17 should look like this:

$(CC) main.c $(INCLUDE) $(OPTS) $(ARFILE) $(LIBS) $(LINKS) -o $@

Thanks!
