### ISSUE TITLE
No tutorial info available

### ISSUE THREAD

**Issue by chriswyatt1** [hahnlab/CAFE#101]
Hey, really excited to use CAFE, but I can't download the tutorial material. I think the link is broken.  [.pdf](https://iu.app.box.com/v/cafetutorial-pdf)

Also, I managed to find a conda container with cafe, but the executable is called `cafe5`. This doesn't link up to the documentation I have managed to see so far, but maybe the tutorial explains this.

Thanks

**Comment by benfulton** [comment]
The tutorial is here: https://github.com/hahnlab/cafe_tutorial

You might want to use CAFE 5 instead. This version isn't being maintained.

**Comment by chriswyatt1** [comment]
Ah thanks so much. I can see now CAFE5: very clear docs and tutorial data :)
