### ISSUE TITLE
Setting random family sizes sometimes sets the size to one more than the max

### ISSUE THREAD

**Issue by benfulton** [hahnlab/CAFE#12]
The function cafe_tree_random_familysize sometimes overflows its array. This is the cause of the issue reported by  张毅 <zyworship at 163.com>

Subject: usage for cafe
Date: December 13, 2016 at 10:57:05 PM EST
 
Is the software can't calculate a big data, such as 52 species and 200 gene family?   In my calculating , the software display "Aborted (core dumped)". And i reduced the data of gene family ,it works and create the report.

**Comment by benfulton** [comment]
Fixed with commit 3dabbceeb70f29f8fb47bafde9ab21afc84e7ee9

**Comment by okokookk** [comment]
Hi.
I also experienced the same issue.
So, I downloaded the newly revised version.
However, this version does not compile.
How do I resolve it?
Below is the compile progress information.

g++ -c -Wall -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/pvalue.o cafe/pvalue.cpp
g++ -c -Wall -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/simerror.o cafe/simerror.cpp
g++ -c -Wall -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/viterbi.o cafe/viterbi.cpp
g++ -c -Wall -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/main.o main.cpp
g++ -Wall -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/cafe release/cafe_family.o release/cafe_main.o release/cafe_report.o release/cafe_tree.o release/cafe_shell.o release/birthdeath.o release/chooseln_cache.o release/phylogeny.o release/tree.o release/fminsearch.o release/grpcmp.o release/histogram.o release/matrix_exponential.o release/regexpress.o release/utils_string.o release/gmatrix.o release/hashtable.o release/mathfunc.o release/memalloc.o release/utils.o release/branch_cutting.o release/cafe_commands.o release/conditional_distribution.o release/error_model.o release/Globals.o release/lambda.o release/lambdamu.o release/log_buffer.o release/reports.o release/likelihood_ratio.o release/pvalue.o release/simerror.o release/viterbi.o release/main.o -lpthread -lm
release/cafe_commands.o: In function `cafe_cmd_load(Globals&, std::vector<std::string, std::allocator<std::string> >)':
cafe_commands.cpp:(.text+0x51d9): undefined reference to `log_param_values(std::ostream&, Globals&)'
collect2: error: ld returned 1 exit status
make: *** [release/cafe] Error 1

**Comment by benfulton** [comment]
Hi okokookk,

That was an issue with this particular commit. Please get the most recent code from the develop branch and this issue should be fixed.

**Comment by benfulton** [comment]
Fixed in version 4.0.1
