### ISSUE TITLE
./configure - no file

### ISSUE THREAD

**Issue by peterthorpe5** [hahnlab/CAFE#16]
Dear CAFE,

I am going to try to use your software but I cannot install it. The instructions say ./configure then make. If I try ./configure or ./configure.ac it fails. Can you please help? Thanks Pete

[pt@gruffalo CAFE-master]$ ./configure
-bash: ./configure: No such file or directory

[pt@gruffalo CAFE-master]$ ./configure.ac
./configure.ac: line 1: syntax error near unexpected token `cafe,'
./configure.ac: line 1: `AC_INIT(cafe, 4.0)'

[pt@gruffalo CAFE-master]$ ls
cafe          configure.ac  example  lib        libtree  main.cpp     mcl2rawcafe.py  README.md         src_docs
CHANGELOG.md  docs          INSTALL  libcommon  LICENSE  Makefile.in  old_log.txt     requirements.txt  tests

**Comment by benfulton** [comment]
Hi Peter,

If you've gotten the source code with GIT there is an extra step: "autoconf" before you run ./configure. If autoconf is not available on your system, please download release 4.0, which does not require the configure step, or wait until next week when release 4.0.1 will be available, and will include the ./configure script as part of the release.

Thanks!

**Comment by peterthorpe5** [comment]
Thank you for your reply Ben.
I have it running now. ☺
Cheers,
Pete

**Comment by kanhu-pcr-code** [comment]
Please add the "autoconf" step in INSTALL file.

**Comment by benfulton** [comment]
We highly recommend installing CAFE from one of the releases, which already have the configure file included.
