### ISSUE TITLE
no binary file - serveral issues

### ISSUE THREAD

**Issue by peterthorpe5** [hahnlab/CAFE#18]
Dear Cafe,

I have downloaded the latest version from github. I have come across several issues:
1) The is no binary file in the download from Github, in the cafe folder or in the release folder..

2) In the documantation the link to the tarbar is broken:
https://hahnlab.github.io/CAFE/download.html    (https://github.com/hahnlab/CAFE/releases/download/v4.0/CAFE.tar.gz)  page 404 webpage not found

3) If I try and install from source using, I get the following error:
    autoconf  (not in the docs yet)
    ./configure
    make
I get the following error:
[pt@gruffalo CAFE]$ make
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/cafe_family.o cafe/cafe_family.c
cafe/cafe_family.c: In function ‘cafe_family_read_query_family’:
cafe/cafe_family.c:288:4: warning: implicit declaration of function ‘strdup’ [-Wimplicit-function-declaration]
    species = strdup(data->array[2]);
    ^
cafe/cafe_family.c:288:12: warning: assignment makes pointer from integer without a cast
    species = strdup(data->array[2]);
            ^
cafe/cafe_family.c: In function ‘cafe_family_read_validate_species’:
cafe/cafe_family.c:331:25: warning: assignment makes pointer from integer without a cast
  param->cv_species_name = strdup(data->array[2]);
                         ^
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/cafe_main.o cafe/cafe_main.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/cafe_report.o cafe/cafe_report.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/cafe_tree.o cafe/cafe_tree.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/cafe_shell.o cafe/cafe_shell.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/birthdeath.o libtree/birthdeath.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/chooseln_cache.o libtree/chooseln_cache.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/phylogeny.o libtree/phylogeny.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/tree.o libtree/tree.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/fminsearch.o libcommon/fminsearch.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/grpcmp.o libcommon/grpcmp.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/histogram.o libcommon/histogram.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/input_values.o libtree/input_values.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/matrix_exponential.o libcommon/matrix_exponential.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/regexpress.o libcommon/regexpress.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/utils_string.o libcommon/utils_string.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/gmatrix.o libcommon/gmatrix.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/hashtable.o libcommon/hashtable.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/mathfunc.o libcommon/mathfunc.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/memalloc.o libcommon/memalloc.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/utils.o libcommon/utils.c
g++ -c -Wall -std=c++11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/branch_cutting.o cafe/branch_cutting.cpp
g++ -c -Wall -std=c++11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/cafe_commands.o cafe/cafe_commands.cpp
g++ -c -Wall -std=c++11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/conditional_distribution.o cafe/conditional_distribution.cpp
g++ -c -Wall -std=c++11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/error_model.o cafe/error_model.cpp
g++ -c -Wall -std=c++11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/gene_family.o cafe/gene_family.cpp
cafe/gene_family.cpp: In function ‘CafeFamily* load_gene_families(std::istream&, int, char)’:
cafe/gene_family.cpp:114:71: error: ‘runtime_error’ was not declared in this scope
     throw runtime_error("Failed to identify species for gene families");
                                                                       ^
make: *** [release/gene_family.o] Error 1

3) Also, the dependancies/ requirements: breathe  can you put more details in the file about this. If you google this you get a lot back.

4) I managed to run version 3.0 which failed to produce any pdf output and therefore the html failed. But did produce results. Have you any idea why this is, could it be fixed in version 4?

cheers,

Pete

**Comment by benfulton** [comment]
Hi Peter,

Thanks for pointing out the website issue! We'll get that fixed.

To install CAFE, please perform the following steps:

1. Download the latest release from
https://github.com/hahnlab/CAFE/releases/latest
2. untar the release with "tar xf CAFE-4.0.1.tar.gz"
3. CD to the appropriate directory
4. ./configure
5. make

The requirements.txt file is involved in creating documentation and is not
required to run the program.

Let me know if you have any other questions!

**Comment by peterthorpe5** [comment]
Hi Ben,

I have downloaded the .tar.gz version. I don’t know how you have compressed this but my linux system does not like it:
[pt@gruffalo Downloads]$ tar -zxvf CAFE-4.0.1.tar.gz
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

So, I downloaded the .zip version. This still fails with “make” (after autoconf, ./configure  then make)
[pt@gruffalo CAFE-4.0.1]$ make
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/cafe_family.o cafe/cafe_family.c
cafe/cafe_family.c: In function ‘cafe_family_read_query_family’:
cafe/cafe_family.c:288:4: warning: implicit declaration of function ‘strdup’ [-Wimplicit-function-declaration]
    species = strdup(data->array[2]);
    ^
cafe/cafe_family.c:288:12: warning: assignment makes pointer from integer without a cast
    species = strdup(data->array[2]);
            ^
cafe/cafe_family.c: In function ‘cafe_family_read_validate_species’:
cafe/cafe_family.c:331:25: warning: assignment makes pointer from integer without a cast
  param->cv_species_name = strdup(data->array[2]);
                         ^
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/cafe_main.o cafe/cafe_main.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/cafe_report.o cafe/cafe_report.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/cafe_tree.o cafe/cafe_tree.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/cafe_shell.o cafe/cafe_shell.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/birthdeath.o libtree/birthdeath.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/chooseln_cache.o libtree/chooseln_cache.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/phylogeny.o libtree/phylogeny.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/tree.o libtree/tree.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/fminsearch.o libcommon/fminsearch.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/grpcmp.o libcommon/grpcmp.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/histogram.o libcommon/histogram.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/input_values.o libtree/input_values.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/matrix_exponential.o libcommon/matrix_exponential.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/regexpress.o libcommon/regexpress.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/utils_string.o libcommon/utils_string.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/gmatrix.o libcommon/gmatrix.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/hashtable.o libcommon/hashtable.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/mathfunc.o libcommon/mathfunc.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/memalloc.o libcommon/memalloc.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/utils.o libcommon/utils.c
g++ -c -Wall -std=c++11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/branch_cutting.o cafe/branch_cutting.cpp
g++ -c -Wall -std=c++11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/cafe_commands.o cafe/cafe_commands.cpp
g++ -c -Wall -std=c++11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/conditional_distribution.o cafe/conditional_distribution.cpp
g++ -c -Wall -std=c++11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/error_model.o cafe/error_model.cpp
g++ -c -Wall -std=c++11 -I cafe -I libtree -I libcommon -O3 -DNDEBUG -o release/gene_family.o cafe/gene_family.cpp
cafe/gene_family.cpp: In function ‘CafeFamily* load_gene_families(std::istream&, int, char)’:
cafe/gene_family.cpp:114:71: error: ‘runtime_error’ was not declared in this scope
     throw runtime_error("Failed to identify species for gene families");
                                                                       ^
make: *** [release/gene_family.o] Error 1

Does any of that make sense?

Cheers,

Pete


The James Hutton Institute is a Scottish charitable company limited by guarantee.
Registered in Scotland No. SC374831
Registered Office: The James Hutton Institute, Invergowrie Dundee DD2 5DA.
Charity No. SC041796

**Comment by benfulton** [comment]
Hi Pete,

It sounds like your download may have gotten corrupted en route. Try
running

>cksum CAFE-4.0.1.tar.gz

The result should be

369945380 19831808 CAFE-4.0.1.tar.gz

If it isn't, you'll need to download the file again.

The "runtime_error not declared in this scope" may indicate that you're
running a version of gcc that is not supported by CAFE. Please let me know
what Linux flavor and gcc version you have, and also send the file
"config.log" that should have been created when you ran the configure
command.

Thanks!

**Comment by blsfoxfox** [comment]
Hi Pete,

You may want to try "tar -xvf CAFE-4.0.1.tar.gz" to extract the files.
I also have the ‘runtime_error’, and the version of my gcc is 4.9.1. Hope that helps.

**Comment by peterthorpe5** [comment]
Hi Ben,

Thanks for your reply. The cksum matches:

[pt@gruffalo Downloads]$ cksum CAFE-4.0.1.tar.gz
369945380 19831808 CAFE-4.0.1.tar.gz

My OS and gcc, another user has replied saying they have error with gcc version 4.9:
[pt@gruffalo Downloads]$ gcc --version
gcc (GCC) 4.9.2 20150212 (Red Hat 4.9.2-6)

I have attached the logfile. I hope you receive attachments on Github(?). I changed my username PATH with $HOME in the log file.

Cheers,

Pete


The James Hutton Institute is a Scottish charitable company limited by guarantee.
Registered in Scotland No. SC374831
Registered Office: The James Hutton Institute, Invergowrie Dundee DD2 5DA.
Charity No. SC041796

**Comment by peterthorpe5** [comment]
Hi blsfoxfox,

My gcc is 4.9.2 so it seems this gcc version may be too old. Let’s see what they say.

Cheers,

Pete

**Comment by peterthorpe5** [comment]
Hi All,

I updated my gcc and it now compiles. I don’t know what your min version would be:

[pt@gruffalo release]$ gcc --version
gcc (GCC) 6.2.1 20160916 (Red Hat 6.2.1-3)

cheers,

Pete

**Comment by benfulton** [comment]
Glad it's working! We will make an effort to support gcc 4.9 in a future
release.

**Comment by benfulton** [comment]
Added #include <stdexcept> to gene_family.cpp to guarantee the inclusion of runtime_error under all compilers.
