### ISSUE TITLE
Cannot allocate memory

### ISSUE THREAD

**Issue by blsfoxfox** [hahnlab/CAFE#19]
Hi,

I am running CAFE 3.1 and get following error while running with the sample data:

(memory_new) Error in memory allocation: 12: Cannot allocate memory

The script is like this:
#!~/bin/cafe
#version
#date
load -i /gpfs0/home/test_data -l logfile.txt -p 0.05
tree (((Chimp:6,Human:6):81,(Mouse:17,Rat:17):70):6,Dog:93)
lambda –s
report resultfile

The test_data looks like this:
Description ID Chimp Human Mouse Rat Dog
EF ENSF00000000004 5 8 6 12 40
HLA2 ENSF00000000007 4 4 3 3 3
HLA1 ENSF00000000014 5 3 5 6 3
RAG1 ENSF00000000015 1 1 1 1 1
IG ENSF00000000020 32 42 51 60 18
ACTIN ENSF00000000027 27 30 22 28 25
OPSIN ENSF00000000029 2 2 2 2 2
HEAVY ENSF00000000030 25 25 23 24 18

Could you please provide some suggestions to solve this?

Thanks!

**Comment by benfulton** [comment]
Hi,

In that version the gene family counts were required to be separated by tabs. Is it possible that your test data file is using spaces as separators rather than tabs?

**Comment by blsfoxfox** [comment]
Yes, you are right. After modify the data file, it runs without error on the test data. However, I met an error while running with my data:

Family information: /gpfs0/home/lzb0021/ouc/raxml/mcmctree/all_vs_all.blast.e10.solar.forHC.hcluster.txt
Log: log.txt
The number of families is 52702
Root Family size : 1 ~ 992
Family size : 0 ~ 952
P-value: 0.050000
Num of Threads: 64
Num of Random: 10000
Expected number of Branch length is 34

I believe this is due to the format of the tree I am using.
The original tree was generated by mcmctree and looks like this:
((((Dmel: 5.831395, Smar: 5.831395): 1.904215, ((Cgig: 4.590050, Pyes: 4.590050): 2.124332, Hrob: 6.714382): 1.021227): 1.140610, ((((((Mmus: 0.895009, Homo: 0.895009): 2.220003, Ggal: 3.115012): 0.404989, Xtro: 3.520001): 0.835017, Drer: 4.355019): 2.743771, Bflo: 7.098790): 1.093337, ((apGBR: 3.836834, apOKI: 3.836834): 2.834284, (Ajap: 4.570981, (Spur: 2.065028, Lvar: 2.065028): 2.505952): 2.100137): 1.521009): 0.684092): 0.590255, (Aque: 8.540078, Mlei: 8.540078): 0.926396);

I just simply kept the integer of each divergent time, and convert it to feed it into CAFE:
((((Dmel:6,Smar:6):2,((Cgig:5,Pyes:5):2,Hrob:7):1):1,((((((Mmus:1,Homo:1):2,Ggal:3):0,Xtro:3):1,Drer:4):3,Bflo:7):1,((apGBR:4,apOKI:4):3,(Ajap:5,(Spur:2,Lvar:2):3):2):1):1):1,(Aque:9,Mlei:9):1)

Is this right way to do it? If not, could you please suggest how to convert the above tree to the format for CAFE, any script or trick?

Thanks

**Comment by benfulton** [comment]
Hi,

You've converted the 0.4 branch length just above Ggal to zero, and CAFE doesn't handle 0-length branches. You'll have to convert it to 1 instead.
