### ISSUE TITLE
ERROR(tree.c): running infix on nonbinary tree

### ISSUE THREAD

**Issue by yongzhiyang2012** [hahnlab/CAFE#21]
I have followed the tutorial of cafe v4.0 to filter the mcl cluster result by python_scripts/cafetutorial_mcl2rawcafe.py , python_scripts/cafetutorial_clade_and_size_filter.py.
When I run "load -i filtered_cafe_input.txt -t 32 -l reports/log_run1.txt
tree ((((((((Oam:5.489859,She:5.489859):4.999583,Goa:10.489442):13.516361,Cow:24.005802):38.721828,Pig:62.727630):19.175412,Hor:81.903042):2.544888,Dog:84.447930):11.519883,Hom:95.967813):62.740158,Opo:158.707971)
lambda -s -t ((((((((1,1)1,1)1,1)1,1)1,1)1,1)1,1)1,1)
report reports/report_run1
", I got the right result.
But when running cafe with the large_filtered_cafe_input.txt and the fixed lambda value, I got the following error:
Family information: large_filtered_cafe_input.txt
Log: reports/log_run2.txtThe number of families is 5
Root Family size : 1 ~ 605
Family size : 0 ~ 580
P-value: 0.01
Num of Threads: 4
Num of Random: 1000
((((((((Oam:5.48986,She:5.48986):4.99958,Goa:10.4894):13.5164,Cow:24.0058):38.7218,Pig:62.7276):19.1754,Hor:81.903):2.54489,Dog:84.4479):11.5199,Hom:95.9678):62.7402,Opo:158.708)
ERROR(tree.c): running infix on nonbinary tree
Lambda has a different topology from the tree
std::exception

So, help me to fix this, please.

**Comment by hhhhqy** [comment]
Have you ever solved this problem? I have the same problem.Hope you can give me some help...
