### ISSUE TITLE
caferror.py - Segmentation fault (core dumped) on first model run

### ISSUE THREAD

**Issue by janphilipoeyen** [hahnlab/CAFE#26]
Hi,
I am trying to estimate a single error model for the whole dataset with a single lambda. However, I get a segmentation fault right when the first error model run (0.4) is about to start. The initial cafe run (-f 1) will run and complete without issue, if enabled.  I get the same error using my dataset and the example data set provided here.

I am using CAFE 4.0.1 and the version of caferror.py that came with it - I will eventually upgrade to get the new filter option for gene family sizes, but I could not see anything related to this issue in the change logs.

Tried moving python script to location where cafe got compiled (usr/local/bin). This made no difference.

I also noticed that the caferror.sh shells which get spawned by caferror.py are hardcoded to use 10 threads. I lowered this to 4, since my system does not have 10 threads available. This also made no difference.

I attached the verbose stdout and also the shell script give to caferror.py with the -i option.  I can also supply any other required files. 

I am running Ubuntu 14.04lts on a machine with 8GB RAM, and an intel i7-3770 with 8x 3,40GhHz cores. I am monitoring the resource use, and it does not seem to be a problem.

I would be very thankful for any suggestions!

Best,
Jan Philip Oeyen

[caferror_stdout.txt](https://github.com/hahnlab/CAFE/files/1340494/caferror_stdout.txt)
[initialshell.txt](https://github.com/hahnlab/CAFE/files/1340671/equalrates_error_shell.txt)

**Comment by janphilipoeyen** [comment]
Hi,
I might have made my comment slightly prematurely. I now tried running the spawend caferror.sh directly, outside of the python script. This produces the same error. I imagine the error I am having might be the same as what is described in [Issue #24](https://github.com/hahnlab/CAFE/issues/24).

I also tried playing with other settings, using errormodel -all option, amongst others. But still nothing seems to affect the problem. I attached the cafe shell spawned by caferror.py when using the example data. I also included the version of the example data I am using.

Best,
Jan Philip Oeyen

[cafe_script.sh.txt](https://github.com/hahnlab/CAFE/files/1340776/cafe_script.sh.txt)
[example_data.txt](https://github.com/hahnlab/CAFE/files/1340778/example_data.txt)

**Comment by benfulton** [comment]
Hi Jan,

My initial thought is that it's a threading problem - try lowering the number of threads all the way down to one and see if that helps. I'll see if I can find another cause though.

**Comment by janphilipoeyen** [comment]
Hi Ben,
I tried changing the threads in the shell script which I give to caferror.py (-i) and also changed the code of caferror.py to only spawn shells using a single thread. I still get a core dump. I attatched the verbose output again. 
If I can provide anything else to be more helpful in tracking the problem, please let me know.

[Caferror_equalrates_1thread_verbose-stdout.txt](https://github.com/hahnlab/CAFE/files/1355321/Caferror_equalrates_1thread_verbose-stdout.txt)

-Jan Philip

**Comment by benfulton** [comment]
Actually, this issue may have been fixed in 4.0.2. From the changelog:

_Errormodel command no longer fails if model has fewer lines than the expected maximum family size_

Can you give 4.0.2 a try?

**Comment by janphilipoeyen** [comment]
Hi,
I updated my cafe version and changed the hardcoding in caferror.py to use -t 1 in the spawned shells. It seems to be running smoothly on 1 core so far. Sorry for the oversight, I only checked the changelog for changes to the python script, when I thought that was the source of the error and did not think to check back again.

-Jan Philip
