### ISSUE TITLE
WARNING

### ISSUE THREAD

**Issue by wdermauw** [hahnlab/CAFE#31]
Hi 

I 'm trying to run CAFEv4.0 on some OrthoFinder data, but I got this warning, before the lambda command:

> Empirical Prior Estimation Result: 13
> Poisson lambda: 0.138575 & Score: inf
> WARNING: Calculated posterior probability for family OG0000000 = 0
> Lambda : 0.14133435029884 & Score: -inf
> .WARNING: Calculated posterior probability for family OG0000000 = 0
> Lambda : 0.14840106781378 & Score: -inf
> .WARNING: Calculated posterior probability for family OG0000000 = 0
> Lambda : 0.13426763278389 & Score: -inf
> .WARNING: Calculated posterior probability for family OG0000000 = 0
> Lambda : 0.13780099154136 & Score: -inf
> .WARNING: Calculated posterior probability for family OG0000000 = 0
> Lambda : 0.14486770905631 & Score: -inf
> .WARNING: Calculated posterior probability for family OG0000000 = 0
> Lambda : 0.14310102967757 & Score: -inf
> .WARNING: Calculated posterior probability for family OG0000000 = 0
> Lambda : 0.13956767092010 & Score: -inf
> .WARNING: Calculated posterior probability for family OG0000000 = 0
> Lambda : 0.14045101060947 & Score: -inf
> .WARNING: Calculated posterior probability for family OG0000000 = 0
> Lambda : 0.14221768998820 & Score: -inf
> .WARNING: Calculated posterior probability for family OG0000000 = 0
> Lambda : 0.14177602014352 & Score: -inf
> .WARNING: Calculated posterior probability for family OG0000000 = 0
> Lambda : 0.14089268045415 & Score: -inf
> .WARNING: Calculated posterior probability for family OG0000000 = 0
> Lambda : 0.14111351537649 & Score: -inf
> .WARNING: Calculated posterior probability for family OG0000000 = 0
> Lambda : 0.14155518522118 & Score: -inf
> .WARNING: Calculated posterior probability for family OG0000000 = 0
> Lambda : 0.14144476776001 & Score: -inf
> .WARNING: Calculated posterior probability for family OG0000000 = 0
> Lambda : 0.14122393283766 & Score: -inf
> .WARNING: Calculated posterior probability for family OG0000000 = 0
> Lambda : 0.14127914156825 & Score: -inf
> .WARNING: Calculated posterior probability for family OG0000000 = 0
> Lambda : 0.14138955902942 & Score: -inf
> .WARNING: Calculated posterior probability for family OG0000000 = 0
> Lambda : 0.14136195466413 & Score: -inf
> .WARNING: Calculated posterior probability for family OG0000000 = 0
> Lambda : 0.14130674593354 & Score: -inf
> .WARNING: Calculated posterior probability for family OG0000000 = 0
> Lambda : 0.14132054811619 & Score: -inf
> .WARNING: Calculated posterior probability for family OG0000000 = 0
> Lambda : 0.14134815248148 & Score: -inf
> .WARNING: Calculated posterior probability for family OG0000000 = 0
> Lambda : 0.14134125139016 & Score: -inf
> .WARNING: Calculated posterior probability for family OG0000000 = 0
> Lambda : 0.14132744920751 & Score: -inf
> .WARNING: Calculated posterior probability for family OG0000000 = 0
> Lambda : 0.14133089975317 & Score: -inf
> .WARNING: Calculated posterior probability for family OG0000000 = 0
> Lambda : 0.14133780084450 & Score: -inf
> .WARNING: Calculated posterior probability for family OG0000000 = 0
> Lambda : 0.14133607557167 & Score: -inf
> .WARNING: Calculated posterior probability for family OG0000000 = 0
> Lambda : 0.14133262502600 & Score: -inf
> .WARNING: Calculated posterior probability for family OG0000000 = 0
> Lambda : 0.14133348766242 & Score: -inf
> .
> Lambda Search Result: 13
> Lambda : 0.14133435029884 & Score: inf
> DONE: Lambda Search or setting, for command:
> lambda -s

OG00000000 species count distribution (18 species) looks the following:

OG0000000	14	114	76	15	241	945	38	79	475	148	204	43	81	188	52	54	18	101

while the species count distribution from other OrthoGroups are not really different from OG0000000

OG0000001	12	2	16	3	211	8	7	4	5	10	18	81	27	1018	4	21	6	42
OG0000002	0	1	15	1	179	5	0	0	2	45	21	10	519	325	2	65	1	117

So, I was wondering If anyone would knew, why I got this warning?

Any help would be much appreciated!

Regards

Wannes

**Comment by binhologia** [comment]
Hi Wannes,

Please have a look at our tutorial: you can't have counts like 519, 325,
etc. These numbers are too big and cause the product of lambda and branch
length (lambda * t) to be > 1. In this case you have saturation of gene
family evolution, and CAFE spits out a likelihood of 0.

The tutorial will guide you through solving this problem... just look for
"large families".

cheers,
Fábio

2017-10-30 6:48 GMT-04:00 wdermauw <notifications@github.com>:

**Comment by wdermauw** [comment]
Dear Fabio

Thank you for your quick reply. I filtered my input dataset for gene families with high counts in any of the 18 species (18_species_test_bis.tab), and reran the analysis (see shell script attached).
I did receive the same error again (see log and results; results_18_species_test_bis.txt.cafe). In addition, I wanted to summarize the output but hen I got the following message:

$ python cafetutorial_report_analysis.py -i results_18_species_test_bis.txt.cafe -o summary_results_18_species_test_bis.txt
Traceback (most recent call last):
  File "cafetutorial_report_analysis.py", line 8, in <module>
    import sys, os, argparse, cafecore as cafecore
ImportError: No module named cafecore

I tried to look for cafecore package but could not find it…

Any suggestion to solve these issue would be much appreciated!

Thank you in advance!

Wannes





-----------------------------------------------------------
Family information: /home/simon/Downloads/18_species_test_bis.tab
Log: logfile_18_species_test_bis.txt
Tree: ((((((Alyc:0.250427,Turt:0.250427):0.250427,((Isca:0.200342,Mocc:0.200342):0.200342,(((Cscu:0.100171,Mmar:0.100171):0.100171,Ptep:0.200342):0.100171,Lpol:0.300513):0.100171):0.100171):0.100171,Smar:0.601026):0.100171,(Dpul:0.584331,(Phum:0.467465,(Tcas:0.350598,(Bmor:0.233732,(Agam:0.116866,Dmel:0.116866):0.116866):0.116866):0.116866):0.116866):0.116866):0.100171,Cele:0.801368):0.100171,(Drer:0.450769,Hsap:0.450769):0.450769)
The number of families is 1112
Root Family size : 1 ~ 30
Family size : 0 ~ 69
P-value: 0.05
Num of Threads: 7
Num of Random: 1000
Empirical Prior Estimation Result: 36
Poisson lambda: 1.988384 & Score: 42492.475027
Lambda : 0.45480757984444 & Score: -inf
.Lambda : 0.47754795883667 & Score: -inf
.Lambda : 0.43206720085222 & Score: -inf
.Lambda : 0.44343739034833 & Score: -inf
.Lambda : 0.46617776934056 & Score: -inf
.Lambda : 0.46049267459250 & Score: -inf
.Lambda : 0.44912248509639 & Score: -inf
.Lambda : 0.45196503247042 & Score: -inf
.Lambda : 0.45765012721847 & Score: -inf
.Lambda : 0.45622885353146 & Score: -inf
.Lambda : 0.45338630615743 & Score: -inf
.Lambda : 0.45409694300094 & Score: -inf
.Lambda : 0.45551821668795 & Score: -inf
.Lambda : 0.45516289826620 & Score: -inf
.Lambda : 0.45445226142269 & Score: -inf
.Lambda : 0.45462992063357 & Score: -inf
.Lambda : 0.45498523905532 & Score: -inf
.Lambda : 0.45489640944988 & Score: -inf
.Lambda : 0.45471875023901 & Score: -inf
.Lambda : 0.45476316504173 & Score: -inf
.Lambda : 0.45485199464716 & Score: -inf
.Lambda : 0.45482978724580 & Score: -inf
.Lambda : 0.45478537244308 & Score: -inf
.Lambda : 0.45479647614376 & Score: -inf
.Lambda : 0.45481868354512 & Score: -inf
.Lambda : 0.45481313169478 & Score: -inf
.Lambda : 0.45480202799410 & Score: -inf
.Lambda : 0.45480480391927 & Score: -inf
.Lambda : 0.45481035576961 & Score: -inf
.Lambda : 0.45480896780703 & Score: -inf
.Lambda : 0.45480619188186 & Score: -inf
.Lambda : 0.45480688586315 & Score: -inf
.
Lambda Search Result: 15
Lambda : 0.45480757984444 & Score: inf
DONE: Lambda Search or setting, for command:
lambda -s 
Running Viterbi algorithm....
Report Done

**Comment by binhologia** [comment]
Hi Wannes,

I don't know where you looked for the cafecore.py script, but it's right
together with the other tutorial (python script) files:
https://iu.app.box.com/v/cafetutorial-files/folder/22161236877

With respect to the -inf scores, it must have been something Ben changed
earlier this morning -- I'll have him have a quick look at it.

cheers,
Fábio

2017-10-30 11:16 GMT-04:00 wdermauw <notifications@github.com>:

**Comment by binhologia** [comment]
(correction) I'll *ask* him -- he might be busy, and in such case will only
be able to respond later.

2017-10-30 13:50 GMT-04:00 Fabio Henrique Kuriki Mendes <
binhologia@gmail.com>:

**Comment by wdermauw** [comment]
Dear Fabio

Thank you for the follow-up. Meanwhile, I figured out the “cafecore” error (I was a bit to hasty ;-( and should have downloaded the other ".py" files).
So, that leaves only the "-inf scores” that I obtain when running my analyses…

Thank you in advance!

Regards

--Wannes

**Comment by wdermauw** [comment]
Dear Fabio

Thank you for the follow-up.

Please find attached a shell script and a input file (with gene counts/gene group/species < 10) that was used for the CAFE analysis and resulted in the -inf error/warning.

Regards

Wannes

**Comment by binhologia** [comment]
Hi Wannes,

I can't seem to find your attachments -- did you drag and drop your files?

Thanks!
cheers,
Fábio

2017-11-01 10:02 GMT-04:00 wdermauw <notifications@github.com>:

**Comment by jmsong2** [comment]
Dear Fabio,
     I cannot open the page https://iu.app.box.com/v/cafetutorial-files/folder/22161236877 to get the tutorial files. Could you send me the python scripts in the page ?

This is my email: jmsong1@outlook.com

**Comment by benfulton** [comment]
Hi, 

Please try the following link:

https://iu.box.com/v/cafe-tutorial-python-scripts

Thanks!

**Comment by KristinaGagalova** [comment]
Hi,
I am having a similar error but the input has a low number of genes actually. I am using the the error correction
```
#!/home/kgagalova/src/CAFE/release/cafe
load -i Orthogroups.GeneCountFilt2.tsv -t 4 -l reports/log_run1.txt
tree ((plambertiana:84.989322,ptaeda:84.989322):55.010678,(((WS77111:17.358173,PG29:17.358173):5.626297,Q903:22.984470):16.691297,pabies:39.675767):100.324233);
errormodel -model reports/run3_caferror_files/cafe_errormodel_0.8125.txt -all
lambda -s
report reports/report_run3
```
Error message:
```
Family information: Orthogroups.GeneCountFilt2.tsv
Log: reports/log_run1.txt
The number of families is 19234
Root Family size : 1 ~ 111
Family size : 0 ~ 139
P-value: 0.01
Num of Threads: 4
Num of Random: 1000
((plambertiana:84.9893,ptaeda:84.9893):55.0107,(((WS77111:17.3582,PG29:17.3582):5.6263,Q903:22.9845):16.6913,pabies:39.6758):100.324)
errormodel: reports/run3_caferror_files/cafe_errormodel_0.8125.txt set.
errormodel: Remember that the rows in the errormodel file have to add up to 1 (rows in the errormodel file correspond to columns in the errormatrix).
errormodel: The program does not check, only renormalizes.
Empirical Prior Estimation Result: (35 iterations)
Poisson lambda: 0.877434 & Score: 128700.086499
Lambda : 0.00312507327180 & Score: -181150.914794
.Lambda : 0.00328132693539 & Score: -180448.335231
.Lambda : 0.00343758059898 & Score: -179795.183564
.Lambda : 0.00359383426257 & Score: -179187.869255
.Lambda : 0.00390634158975 & Score: -178092.808623
.Lambda : 0.00421884891693 & Score: -177132.023320
.Lambda : 0.00484386357130 & Score: -175541.762442
.Lambda : 0.00546887822566 & Score: -174302.099623
.Lambda : 0.00671890753438 & Score: -172568.909954
.Lambda : 0.00796893684310 & Score: -171505.256691
.WARNING: Calculated posterior probability for family OG0000056 = 0
Lambda : 0.01046899546054 & Score: -inf
.Lambda : 0.00921896615182 & Score: -170877.977366
...
```
Number of genes for the gene family
```
OG0000056       10      10      14      42      8       14
```
Is there something wrong with my script? 
Thank you in advance
Kristina

**Comment by benfulton** [comment]
That should not affect the final result. The warning refers specifically to the optimizer trying the value 0.01046899546054, which failed on that particular family, but that happens sometimes. The optimizer simply went on to a new value and tried again. It appears to have been successful with 0.00921896615182.

**Comment by KristinaGagalova** [comment]
Hi, 
The calculated lambda is 0.01 which is higher than the one that was calculated without error correction. I tried a couple of error correction factors and I am having the same output. 
Is there a way to troubleshoot this bug and see what causes it?
Thank you in advance

**Comment by benfulton** [comment]
I'm not sure what error you're seeing, but you might have better luck sending an email to hahnlabcafe@googlegroups.com . Describe what you're seeing and what you think you ought to see.

**Comment by KristinaGagalova** [comment]
Looks like my mail bounces back. Do I need to be a member of the group?

**Comment by benfulton** [comment]
Yes, but you can join automatically and then leave again if you so desire :)
