### ISSUE TITLE
Install 

### ISSUE THREAD

**Issue by jprmachado** [hahnlab/CAFE#36]
I am getting this error after "make" command

Makefile:116: recipe for target 'release/error_model.o' failed
make: *** [release/error_model.o] Error 1

solved, changed:

isnan to std::isnan

isinf to std::isinf

**Comment by jprmachado** [comment]
cafe/error_model.cpp: In function ‘double __loglikelihood_pairs_from_double_measure(double*, void*)’:
cafe/error_model.cpp:474:32: error: ‘isnan’ was not declared in this scope
                 if (isnan(score) || isinf(-score) || !std::isfinite(score)) {
                                ^
cafe/error_model.cpp:474:32: note: suggested alternative:
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from cafe/error_model.cpp:2:
/usr/include/c++/5/cmath:641:5: note:   ‘std::isnan’
     isnan(_Tp __x)
     ^
cafe/error_model.cpp:474:49: error: ‘isinf’ was not declared in this scope
                 if (isnan(score) || isinf(-score) || !std::isfinite(score)) {
                                                 ^
cafe/error_model.cpp:474:49: note: suggested alternative:
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from cafe/error_model.cpp:2:
/usr/include/c++/5/cmath:621:5: note:   ‘std::isinf’
     isinf(_Tp __x)
     ^
cafe/error_model.cpp: In function ‘ErrorMeasure* estimate_error_double_measure(std::ostream&, std::istream*, std::istream*, int, int, int, int)’:
cafe/error_model.cpp:597:23: error: ‘isnan’ was not declared in this scope
    if (!isnan(*pfm->fv) && !isinf(*pfm->fv) && abs(minscore - (*pfm->fv)) < pfm
                       ^
cafe/error_model.cpp:597:23: note: suggested alternative:
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from cafe/error_model.cpp:2:
/usr/include/c++/5/cmath:641:5: note:   ‘std::isnan’
     isnan(_Tp __x)
     ^
cafe/error_model.cpp:597:43: error: ‘isinf’ was not declared in this scope
    if (!isnan(*pfm->fv) && !isinf(*pfm->fv) && abs(minscore - (*pfm->fv)) < pfm
                                           ^
cafe/error_model.cpp:597:43: note: suggested alternative:
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from cafe/error_model.cpp:2:
/usr/include/c++/5/cmath:621:5: note:   ‘std::isinf’
     isinf(_Tp __x)
     ^
cafe/error_model.cpp: In function ‘ErrorMeasure* estimate_error_true_measure(std::ostream&, const char*, const char*, int, int, int, int)’:
cafe/error_model.cpp:715:23: error: ‘isnan’ was not declared in this scope
    if (!isnan(*pfm->fv) && !isinf(*pfm->fv) && abs(minscore - (*pfm->fv)) < pfm
                       ^
cafe/error_model.cpp:715:23: note: suggested alternative:
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from cafe/error_model.cpp:2:
/usr/include/c++/5/cmath:641:5: note:   ‘std::isnan’
     isnan(_Tp __x)
     ^
cafe/error_model.cpp:715:43: error: ‘isinf’ was not declared in this scope
    if (!isnan(*pfm->fv) && !isinf(*pfm->fv) && abs(minscore - (*pfm->fv)) < pfm
                                           ^
cafe/error_model.cpp:715:43: note: suggested alternative:
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from cafe/error_model.cpp:2:
/usr/include/c++/5/cmath:621:5: note:   ‘std::isinf’
     isinf(_Tp __x)

**Comment by benfulton** [comment]
Tests for compilation under various compiler/os combinations have been added, and hopefully this one in particular now compiles.
