### ISSUE TITLE
get ultrametric tree

### ISSUE THREAD

**Issue by ChengYunazhi** [hahnlab/CAFE#37]
Hi,
  
  in the  manual using r8s to get a ultrametric tree, nsites was specified. whether nsites is the number of sites in alignment (include gaps) or sites used to infer tree (if one site has same base in all species, without variation among species, tree infering algorithm will not use it, so this site should include in nsites or not?)

All the best

**Comment by ChengYunazhi** [comment]
@hahnlab Hi,

in the manual using r8s to get a ultrametric tree, nsites was specified. whether nsites is the number of sites in alignment (include gaps) or sites used to infer tree (if one site has same base in all species, without variation among species, tree infering algorithm will not use it, so this site should include in nsites or not?)

All the best

**Comment by benfulton** [comment]
Please don't open CAFE issues on Github for bioinformatics questions. Send a message to the CAFE Google group (https://groups.google.com/forum/#!forum/hahnlabcafe ) if you think the question would be best answered by CAFE experts. In this case it sounds more like you would get a better answer if you posted the question to Biostars (https://www.biostars.org/ ). Feel free to use the CAFE tag there.

The nsites parameter is simply the total number of columns in the alignment(s) used to construct your species tree. Note that for input to r8s, the species tree must have branch lengths in terms of relative number of substitutions (as commonly given from maximum likelihood programs like RAxML). I'm not entirely sure how OrthoFinder does species tree inference, but as long as it uses a multiple-sequence alignment and infers a tree with branch lengths in relative number of substitutions, then you should easily be able to count nsites from the alignment.
