### ISSUE TITLE
GO enrichment for family that rapid evolved

### ISSUE THREAD

**Issue by zy041225** [hahnlab/CAFE#39]
Hi,

I would like to know what kinds of genes that got rapidly evolved during evolution (e.g. rapidly expanded in mammalian clade). Thus, I think I could perform a GO enrichment analysis on the genes from the families that got a rapid expansion. However, I'm not sure which to choose to be the background for the enrichment. Could I infer the ancestral genes based on the CAFE's result, then perform the analysis using ancestral gene set as background?

Best,
Yang

**Comment by benfulton** [comment]
Hi Yang,

Please don't open CAFE issues on Github for bioinformatics questions. Send a message to the CAFE Google group (https://groups.google.com/forum/#!forum/hahnlabcafe ) if you think the question would be best answered by CAFE experts. In this case it sounds more like you would get a better answer if you  posted the question to Biostars (https://www.biostars.org/ ). Feel free to use the CAFE tag there.

**Comment by zy041225** [comment]
Thanks, I'll try at Biostars.
