### ISSUE TITLE
make on Mac

### ISSUE THREAD

**Issue by maedat** [hahnlab/CAFE#45]
I will share the error and on the solution which occurred on Mac.

I got errors when did "make" on Mac High Sierra 10.13.4

> cafe / error_model.cpp: 473: 55: error: no member named 'isfinite' in namespace 'std'; did you mean 'finite'?
> cafe / lambda.cpp: 706: 18: error: no member named 'isnan' in namespace 'std'

To resolved these issue, I added below line 
` #include <cmath>`
on each files; cafe / lambda.cpp, cafe / error_model.cpp.

Enjoy!

**Comment by benfulton** [comment]
Thanks! We'll make this addition for the next release as well.

**Comment by macmanes** [comment]
@benfulton, have to add `#include <cmath>` to `cafe/cafe_commands.cpp` as well, in v4.2.

**Comment by benfulton** [comment]
Thanks! So hard to duplicate Mac environments.
