### ISSUE TITLE
Maximum value for  λ × t < 1 doesn't hold true for µ

### ISSUE THREAD

**Issue by josiahseaman** [hahnlab/CAFE#50]
> The product of λ or µ and the depth of the tree should not exceed one (i.e.,
> λ × t < 1 and µ × t < 1 must be true; where t is the time from tips to the
> root). 

While verifying my results, I noticed the death rate was higher than 1 / total branch length.  From root to tip I have two branches 42 + 37 = 79.  Cafe estimated the death rate at Mu = 0.0202 * 79 = 1.5958 

There was no warning in the output that I could see.  It may just be that this restriction doesn't apply to µ like the manual states, or it may be that the check overlooks this scenario incorrectly.

Related to this, in the documentation there are placeholders that were never filled in:
**Cafe Manual March 14, 2017**
> If the product of λ and the distance from the tips to the root is greater than 1,
> then CAFE will not return accurate results. If λ is specified by the user, this
> problem is seen as “@@”. If the λ-search option is used, then the value of λ output
> will be the maximum possible for λ × t < 1. If this is a problem, CAFE will print
> a caution message and “@@” will appear before the Newick-formatted tree in the
> output. In our experience, this is the most common error encountered by users.

Why does this restriction exist in the first place?  Wouldn't λ × t > 1 simply mean that gene families have more than doubled on average?

**Comment by benfulton** [comment]
No. If the lambda times the time is greater than one, it means that the number of changes that are likely to have occurred is so large that a single character may have changed more than once. In this case it becomes impossible to infer the total number of changes based only on the differences.

**Comment by josiahseaman** [comment]
In the case where I'm estimating birth and death rates separately, is it invalid if the death rate (and only the death rate) times time is higher than 1?  If you have an ancestral family size of 28 and a branch where that is reduced to 12, that's more than a 2x reduction along that path.   I'm studying a case of diploidization after a whole genome location, so I'm expecting a 2x reduction in size to be the norm and my results mostly coincide with that.

**Comment by benfulton** [comment]
I don't believe there is any special-case code in CAFE that would invalidate that scenario. But I think the science is getting beyond me - you should post a message to https://groups.google.com/forum/#!forum/hahnlabcafe to get better responses.

**Comment by josiahseaman** [comment]
Ok, thanks for the clarification.
