### ISSUE TITLE
No configure file in the directory

### ISSUE THREAD

**Issue by lcottret** [hahnlab/CAFE#54]
Hi,

Everything is in the title : I can not install CAFE because the "./configure" is missing.

Regards, 
Ludo

**Comment by benfulton** [comment]
Hi Ludo,

What version are you trying to install?

**Comment by faguil** [comment]
Hi Ben,

Same problem here, I downloaded the master version that is in this repository. I tried to install the 4.2 version from https://hahnlab.github.io/CAFE/ and got the following error

Makefile110: recipe for target 'release/branch_cutting.o' failed

I have gcc version 5.4.0

Any help will be appreciated

Thanks in advance,

Felipe

**Comment by benfulton** [comment]
If you want to get the latest source code, you must have the "autotools"
package installed on your computer and run "autoconf".  This will create
the required "./configure" file. This is not recommended unless you plan on
developing the CAFE code itself.

Can you send the entire output of the "make" command? What flavor of Linux
are you using?

**Comment by faguil** [comment]
Hi Ben,

This is the output of the make command:

make
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -fopenmp -O3 -DNDEBUG -o release/cafe_family.o cafe/cafe_family.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -fopenmp -O3 -DNDEBUG -o release/cafe_main.o cafe/cafe_main.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -fopenmp -O3 -DNDEBUG -o release/cafe_report.o cafe/cafe_report.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -fopenmp -O3 -DNDEBUG -o release/cafe_tree.o cafe/cafe_tree.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -fopenmp -O3 -DNDEBUG -o release/cafe_shell.o cafe/cafe_shell.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -fopenmp -O3 -DNDEBUG -o release/birthdeath.o libtree/birthdeath.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -fopenmp -O3 -DNDEBUG -o release/chooseln_cache.o libtree/chooseln_cache.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -fopenmp -O3 -DNDEBUG -o release/phylogeny.o libtree/phylogeny.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -fopenmp -O3 -DNDEBUG -o release/tree.o libtree/tree.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -fopenmp -O3 -DNDEBUG -o release/grpcmp.o libcommon/grpcmp.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -fopenmp -O3 -DNDEBUG -o release/histogram.o libcommon/histogram.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -fopenmp -O3 -DNDEBUG -o release/input_values.o libtree/input_values.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -fopenmp -O3 -DNDEBUG -o release/matrix_exponential.o libcommon/matrix_exponential.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -fopenmp -O3 -DNDEBUG -o release/regexpress.o libcommon/regexpress.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -fopenmp -O3 -DNDEBUG -o release/utils_string.o libcommon/utils_string.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -fopenmp -O3 -DNDEBUG -o release/gmatrix.o libcommon/gmatrix.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -fopenmp -O3 -DNDEBUG -o release/hashtable.o libcommon/hashtable.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -fopenmp -O3 -DNDEBUG -o release/mathfunc.o libcommon/mathfunc.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -fopenmp -O3 -DNDEBUG -o release/memalloc.o libcommon/memalloc.c
gcc -c -Wall -std=c11 -I cafe -I libtree -I libcommon -fopenmp -O3 -DNDEBUG -o release/utils.o libcommon/utils.c
g++ -c -Wall -std=c++11 -I cafe -I libtree -I libcommon -fopenmp -O3 -DNDEBUG -o release/branch_cutting.o cafe/branch_cutting.cpp
In file included from /usr/local/include/assert.h:5:0,
                 from libtree/birthdeath.h:4,
                 from libtree/family.h:5,
                 from cafe/branch_cutting.h:7,
                 from cafe/branch_cutting.cpp:6:
/usr/local/include/except.h:15:32: error: conflicting declaration ‘typedef struct Except_Frame_T* Except_Frame_T’
 typedef struct Except_Frame_T *Except_Frame_T;
                                ^
/usr/local/include/except.h:15:16: note: previous declaration as ‘struct Except_Frame_T’
 typedef struct Except_Frame_T *Except_Frame_T;
                ^
/usr/local/include/except.h:17:18: error: field ‘prev’ has incomplete type ‘Except_Frame_T’
   Except_Frame_T prev;
                  ^
/usr/local/include/except.h:16:8: note: definition of ‘struct Except_Frame_T’ is not complete until the closing brace
 struct Except_Frame_T {
        ^
Makefile:110: recipe for target 'release/branch_cutting.o' failed
make: *** [release/branch_cutting.o] Error 1


I am using Linux Ubuntu 1604 LTS

Cheers,

Felipe

**Comment by benfulton** [comment]
I think this is a problem with your system. Have you installed the software GMAP/GSNAP?  It seems to add two files in /usr/local/include/ - except.h and assert.h - which cause these errors.

You can remove them with

```
cd /usr/local/include
sudo mv assert.h assert.h.bad
sudo mv except.h except.h.bad
```

(Although if GMAP/GSNAP relies on these files there may be other errors)

**Comment by faguil** [comment]
Yes, I have installed GMAP in that machine, which works fine. 

Hmmm, I will give a try CAFE in another PC

Thanks for your help
