### ISSUE TITLE
Generating report does not finish

### ISSUE THREAD

**Issue by suz11001** [hahnlab/CAFE#55]
Hi,

I am currently trying to execute a very simple CAFE analysis (17 species and 19690 gene families). Cafe is executed with the following script: 

```
load -i Orthogroups.CAFE.filtered.renamed.txt -t 8 -l log.txt -p 0.01

tree ((spikeMoss:295.354,moss:295.354)1:295.354,((amborella:430.724,((arabidopsisThaliana:258.434,(grape:172.29,(jatrophaCurcas:86.1448,corkOak:86.1448)1:86.1448)1:86.1448)1:86.1448,(sorghum:172.29,rice:172.29)1:172.29)1:86.1448)1:86.1448,(ginkgoBiloba:443.03,(douglasFir:369.192,((sitkaSpruce:147.677,norwaySpruce:147.677)1:147.677,(sugarPine:221.515,(pinusCanariensis:147.677,(loblollyPine:73.8384,pinusPatula:73.8384)1:73.8384)1:73.8384)1:73.8384)1:73.8384)1:73.8384)1:73.8384)1:73.8384);

lambda -s                                     

report CAFEout
```

However, the program never finishes generating the report (I killed the job after 20 days). I've tried running it on 8 cores with 50G of memory on an HPC but with no luck. The viterbi algorithm just keeps running forever it seems. 

I've tried running CAFE on specific parts of the tree. However, this only works when using only angiosperms with the following tree:
`(amborella:430.724,((arabidopsisThaliana:258.434,(grape:172.29,(jatrophaCurcas:86.1448,corkOak:86.1448)1:86.1448)1:86.1448)1:86.1448,(sorghum:172.29,rice:172.29)1:172.29)1:86.1448)`

If I try to use gymnosperms with the following tree:
`(ginkgoBiloba:443.03,(douglasFir:369.192,((sitkaSpruce:147.677,norwaySpruce:147.677)1:147.677,(sugarPine:221.515,(pinusCanariensis:147.677,(loblollyPine:73.8384,pinusPatula:73.8384)1:73.8384)1:73.8384)1:73.8384)1:73.8384)1:73.8384);`

Then no report is generated. 

*Other things that I have tried:
1. Filtering very large gene families
2. When testing only gymnosperms, removing gene families with size 0 across all species
3. Making sure the tree is ultrametric
4. More cores and more memory

Any guidance would be very much appreciated!

P.S. In all cases I am receiving the warning calculated posterior probability for specific gene family is zero. Don't know if that will help in trouble shooting... 

Thank you!

**Comment by ChengYunazhi** [comment]
just set "-t 1", turn off parallel computing.
