### ISSUE TITLE
max counts variance & nos. of λs?

### ISSUE THREAD

**Issue by anandksrao** [hahnlab/CAFE#58]
Greetings to CAFE users and authors,

I want to measure rate of gene birth and death across each branch of my tree of ~ 50 species.
And I want to do this for 3 different gene families, corresponding to 3 different Pfam domains.

Obviously, I am considering using CAFE for this purpose. I've scanned the ver 4.0's manual and I already have a few questions:

1. Is there a limit on the number of different λs that can be assumed at the beginning? 
Can it be same as number of species analysed (in my case ~ 50)?

2. What is the maximum variance in gene counts that will allow proper CAFE execution?

3. Can permissible gene count variation only be empirically determined or even theoretically predicted? If latter is true, how?

4. Finally, for my purposes does it make a difference if I use CAFE ver 4.2 or the most recent ver 5?

I look forward to your advice. Thanks!

**Comment by benfulton** [comment]
Questions answered on the mailing list.
