### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by fantasticair** [hahnlab/CAFE#61]
Hello ,
I install this software,when use `make`,get the error is `gcc: error trying to exec 'cc1': execvp: No such file or directory`

**Comment by benfulton** [comment]
This most likely is a problem with your system. Try running the following command (for Ubuntu only)

 

$ sudo apt-get install --reinstall build-essential

 

--

Ben Fulton

Research Applications and Deep Learning

Research Technologies

Indiana University

E-Mail:  <mailto:befulton@iu.edu> befulton@iu.edu
