### ISSUE TITLE
cafetutorial_longest_iso.py error

### ISSUE THREAD

**Issue by NINGCHINA** [hahnlab/CAFE#63]
when I check cafetutorial_longest_iso.py at [https://iu.app.box.com/v/cafetutorial-files/folder/22161186238?page=1](url) , I found the script will choose the shortest isoform rather than the longest isoform. The mistake stays between line of 42 and 46:
```
try:
    if seq_len < longest_iso_dict[seq_id]:
        longest_iso_dict[seq_id] = seq_len
except:
    longest_iso_dict[seq_id] = seq_len

```

**Comment by benfulton** [comment]
Ouf. You would think this would have been noticed before now. The tutorial script has been updated accordingly.

**Comment by NINGCHINA** [comment]
👍 Very timely！
