### ISSUE TITLE
Can I use this tool for gene gain and loss analysis of Bacterial (Prokaryotic) genome 

### ISSUE THREAD

**Issue by dineshkumarsrk** [hahnlab/CAFE#68]
I would like to conduct a gene gain and loss analysis in my bacterial species of interest, for that I intended to use your CAFE tool. However, my literature survey concluded that, CAFE tool has been used for eukaryotic genomes only. Therefore, please let me know, CAFE tool is only for Eukaryotic organisms genome?. Can't we use CAFE tool for bacterial genome?

**Comment by benfulton** [comment]
Please ask and answer questions here: https://groups.google.com/forum/#!forum/hahnlabcafe
