### ISSUE TITLE
Can we use log transformed data rather than counts to account for zero values?

### ISSUE THREAD

**Issue by Jigyasa3** [hahnlab/CAFE#69]
Hey @benfulton @fkmendes @traviscibot 

I was wondering if you have any suggestions for data with a lot of zero values? I read your 2013 paper on error value estimation which accounts for genome sequencing and annotation bias. I wanted to ask if the error value accounts for zeroes in the data (either due to the absence of genes or sequencing bias). Or would you suggest some sort of transformation of data before measuring birth-death?

Thanks!

**Comment by benfulton** [comment]
Hi,

Please post your question to the user group at https://groups.google.com/forum/#!forum/hahnlabcafe for an answer to your question.
