### ISSUE TITLE
error in report out

### ISSUE THREAD

**Issue by hfl112** [hahnlab/CAFE#72]
*** Error in `cafe': double free or corruption (!prev): 0x00007f1229738ce0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7344f)[0x7f12585e844f]
/lib64/libc.so.6(+0x78cbe)[0x7f12585edcbe]
/lib64/libc.so.6(+0x79997)[0x7f12585ee997]
cafe[0x429cf9]
cafe[0x42c140]
cafe[0x41be86]
/lib64/libpthread.so.0(+0x81b3)[0x7f1258c2c1b3]
/lib64/libc.so.6(clone+0x6d)[0x7f125865bfed]

Aborted (core dumped)
____________
seems that the file is too big?
can i use multiple threads to circumvent this problem? is multiple threads available in CAFE?

**Comment by hfl112** [comment]
actually I have used cafe several times, this is the first time I encounter this problem

**Comment by majianxiang** [comment]
> 
> 
> actually I have used cafe several times, this is the first time I encounter this problem

You can use  the option "-t" of the conmand "load"|  to execute the program.

**Comment by hfl112** [comment]
> > actually I have used cafe several times, this is the first time I encounter this problem
> 
> You can use the option "-t" of the conmand "load"| to execute the program.

I have used 60 cpus to rerun this, still go this error in report out. any ideas to solve the problem?

**Comment by benfulton** [comment]
The problem with using that many CPU's is that you may uncover underlying race conditions in the code that we haven't found using fewer CPU's. I would use the -t option to use a smaller number of cores and see if that works. Are you using v4.2.1 ?

**Comment by hfl112** [comment]
> The problem with using that many CPU's is that you may uncover underlying race conditions in the code that we haven't found using fewer CPU's. I would use the -t option to use a smaller number of cores and see if that works. Are you using v4.2.1 ?

Thanks for the help, after I upgraded CAFE to v4.2.1, the problem have been solved
