### ISSUE TITLE
cafetutorial_longest_iso.py produces output of empty file

### ISSUE THREAD

**Issue by madhubioinfo** [hahnlab/CAFE#74]
I am trying to run python2.7 cafetutorial_longest_iso.py -d ../input/

It is creating longest files but all of them are empty without any error. any recommendations?

**Comment by benfulton** [comment]
Are you sure that the input directory contains non-empty, valid fasta files?

**Comment by madhubioinfo** [comment]
no input file is not empty, im sure.

**Comment by benfulton** [comment]
Would it be possible to attach one of the files here? Or a truncated version if they are very large.

**Comment by madhubioinfo** [comment]
hi, I bypassed that step and started from orthomcl cluster parsing, and i am stuck at  different place ,  this is my command python ../python_scripts/cafetutorial_prep_r8s.py -i newick_again.tree -o r8s_ctl_file.txt -s 471168 -p ’geo,Rhiir’ -c ’269’ and im unable to understand the error 


 File "../python_scripts/cafetutorial_prep_r8s.py", line 59
    print "\nRunning cafetutorial_clade_and_size_filter.py as a standalone...\n"
                                                                               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("\nRunning cafetutorial_clade_and_size_filter.py as a standalone...\n")?

this is my tree file
(geo:0.1802219013,((Gigro1:0.1156071494,div:0.1330229219):0.0342554937,(Rhice:0.0408646186,Rhiir:0.0468497155):0.087742045):0.0573943276,(Morel:0.2854187907,((Mucci:0.0978162948,Rhimi:0.1203169283):0.0734937446,Phybl:0.1465663475):0.175521913):0.113504486);

**Comment by benfulton** [comment]
That indicates you're using a Python 3 to run the script. Try using the python2.7 you were using before.

**Comment by madhubioinfo** [comment]
after running the r8s i still have a problem with the output when i parse it

I have pasted tail of my output file

Results of cross validation analysis for tree nj_tree
Method = Penalized Likelihood

log10
smooth  smooth          Sq Error        Chi Square Error
--------------------------------------------------------------------------------
  0.00       1            0.00    0.00  (Failed)
  0.50     3.2            0.00    0.00  (Failed)
  1.00      10            0.00    0.00  (Failed)
  1.50      32            0.00    0.00  (Failed)
  2.00   1e+02            0.00    0.00  (Failed)
  2.50  3.2e+02           0.00    0.00  (Failed)
  3.00   1e+03            0.00    0.00  (Failed)
  3.50  3.2e+03           0.00    0.00  (Failed)
********************************************************************************

Optimum:   0.00      1            0.00    0.00
WARNING: Cross validation procedure had errors: optimum may be incorrect
********************************************************************************

[Printing tree 1]

[CHRONOGRAM of tree nj_tree]
!FATAL ERROR!********************* WARNING **********************

Times do not appear to have been set on trees; try converting lengths to time

****************************************************

**Comment by benfulton** [comment]
You might be able to get help with r8s on the CAFE mailing list. 

https://groups.google.com/forum/#!forum/hahnlabcafe
