### ISSUE TITLE
No species was found in the family list

### ISSUE THREAD

**Issue by ajkshdkjahdka** [hahnlab/CAFE#76]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ajkshdkjahdka** [comment]
Hi,i got a problem like this and i dont kown why:
Family information: /gpfs/scratch/jliu/new_orth/Results_Mar15_2/cafe.data.4
Log: log_run12.txt
The number of families is 20358
Root Family size : 1 ~ 262
Family size : 0 ~ 260
P-value: 0.05
Num of Threads: 4
Num of Random: 1000
((((Lipotes:52.3196,Balae:52.3196):122.552,Homo:174.871):62.124,Rattus:236.996):386.767,(((((Chry:34.6421,Terra:34.6421):43.7381,(((Gopha:26.3718,Gophe:26.3718):31.4675,Chelon:57.8393):8.58383,WC:66.4231):11.9571):18.9088,CheMyd:97.2889):63.7111,Pelo:161):181.094,gallus:342.094):281.668)
No species 'balae' was found in the family list

and this is my cafe.sh:
#!cafe 
load -i /gpfs/scratch/jliu/new_orth/Results_Mar15_2/cafe.data.4 -t 4 -l log_run12.txt -p 0.05
tree ((((Lipotes:52.319557,Balae:52.319557):122.551938,Homo:174.871495):62.124008,Rattus:236.995502):386.766599,(((((Chry:34.642108,Terra:34.642108):43.738076,(((Gopha:26.371769,Gophe:26.371769):31.467488,Chelon:57.839257):8.583830,WC:66.423087):11.957097):18.908766,CheMyd:97.288950):63.711050,Pelo:161.000000):181.093633,gallus:342.093633):281.668468);
lambda -s -t ((((1,1),1),1),(((((1,1),(((1,1),1),1)),1),1),1));
report resultfile1

this is my cafe.data.4 file:
(null)	Balae	CheMyd	Chelon	Chry	Gopha	Gophe	Homo	Lipotes	Pelo	Rattus	Terra	WC	gallus
(null)	OG0000000	6	89	68	190	39	145	29	1	4	63	160	2	10	
(null)	OG0000001	28	30	26	46	36	64	47	3	37	210	55	1	18	
(null)	OG0000002	1	64	58	105	55	148	6	0	47	4	56	44	0	
(null)	OG0000003	67	6	11	16	30	11	185	28	10	99	6	90	0	
(null)	OG0000004	4	52	48	75	67	59	10	3	67	3	63	27	34	
(null)	OG0000005	3	29	24	97	35	128	1	2	60	6	113	1	1	
(null)	OG0000006	1	58	50	102	52	101	20	1	33	1	50	29	1

could you please tell why? thank you very much!

**Comment by benfulton** [comment]
Please ask usage questions in the forum. https://groups.google.com/forum/#!forum/hahnlabcafe
