### ISSUE TITLE
error when make

### ISSUE THREAD

**Issue by wuxiaopei0509** [hahnlab/CAFE#77]
Dear developer
When I make during install ,it occurs the error as follows:
g++ -c -Wall -std=c++11 -I cafe -I libtree -I libcommon -fopenmp -O3 -DNDEBUG -o release/cafe_commands.o cafe/cafe_commands.cpp
cafe/cafe_commands.cpp: 在函数‘bool is_nearly_equal(double, double)’中:
cafe/cafe_commands.cpp:1065:26: 错误：调用重载的‘abs(double)’有歧义
     return std::abs(x - y) <= epsilon * std::abs(x);
                          ^
In file included from /usr/local/include/c++/5.4.0/cstdlib:72:0,
                 from /usr/local/include/c++/5.4.0/ext/string_conversions.h:41,
                 from /usr/local/include/c++/5.4.0/bits/basic_string.h:5249,
                 from /usr/local/include/c++/5.4.0/string:52,
                 from /usr/local/include/c++/5.4.0/stdexcept:39,
                 from /usr/local/include/c++/5.4.0/array:38,
                 from /usr/local/include/c++/5.4.0/tuple:39,
                 from /usr/local/include/c++/5.4.0/bits/stl_map.h:63,
                 from /usr/local/include/c++/5.4.0/map:61,
                 from cafe/cafe_commands.cpp:97:
/usr/include/stdlib.h:770:12: 附注：candidate: int abs(int)
 extern int abs (int __x) __THROW __attribute__ ((__const__)) __wur;
            ^
In file included from /usr/local/include/c++/5.4.0/ext/string_conversions.h:41:0,
                 from /usr/local/include/c++/5.4.0/bits/basic_string.h:5249,
                 from /usr/local/include/c++/5.4.0/string:52,
                 from /usr/local/include/c++/5.4.0/stdexcept:39,
                 from /usr/local/include/c++/5.4.0/array:38,
                 from /usr/local/include/c++/5.4.0/tuple:39,
                 from /usr/local/include/c++/5.4.0/bits/stl_map.h:63,
                 from /usr/local/include/c++/5.4.0/map:61,
                 from cafe/cafe_commands.cpp:97:
/usr/local/include/c++/5.4.0/cstdlib:166:3: 附注：candidate: long int std::abs(long int)
   abs(long __i) { return __builtin_labs(__i); }
   ^
/usr/local/include/c++/5.4.0/cstdlib:174:3: 附注：candidate: long long int std::abs(long long int)
   abs(long long __x) { return __builtin_llabs (__x); }
   ^
cafe/cafe_commands.cpp:1065:51: 错误：调用重载的‘abs(double&)’有歧义
     return std::abs(x - y) <= epsilon * std::abs(x);
                                                   ^
In file included from /usr/local/include/c++/5.4.0/cstdlib:72:0,
                 from /usr/local/include/c++/5.4.0/ext/string_conversions.h:41,
                 from /usr/local/include/c++/5.4.0/bits/basic_string.h:5249,
                 from /usr/local/include/c++/5.4.0/string:52,
                 from /usr/local/include/c++/5.4.0/stdexcept:39,
                 from /usr/local/include/c++/5.4.0/array:38,
                 from /usr/local/include/c++/5.4.0/tuple:39,
                 from /usr/local/include/c++/5.4.0/bits/stl_map.h:63,
                 from /usr/local/include/c++/5.4.0/map:61,
                 from cafe/cafe_commands.cpp:97:
/usr/include/stdlib.h:770:12: 附注：candidate: int abs(int)
 extern int abs (int __x) __THROW __attribute__ ((__const__)) __wur;
            ^
In file included from /usr/local/include/c++/5.4.0/ext/string_conversions.h:41:0,
                 from /usr/local/include/c++/5.4.0/bits/basic_string.h:5249,
                 from /usr/local/include/c++/5.4.0/string:52,
                 from /usr/local/include/c++/5.4.0/stdexcept:39,
                 from /usr/local/include/c++/5.4.0/array:38,
                 from /usr/local/include/c++/5.4.0/tuple:39,
                 from /usr/local/include/c++/5.4.0/bits/stl_map.h:63,
                 from /usr/local/include/c++/5.4.0/map:61,
                 from cafe/cafe_commands.cpp:97:
/usr/local/include/c++/5.4.0/cstdlib:166:3: 附注：candidate: long int std::abs(long int)
   abs(long __i) { return __builtin_labs(__i); }
   ^
/usr/local/include/c++/5.4.0/cstdlib:174:3: 附注：candidate: long long int std::abs(long long int)
   abs(long long __x) { return __builtin_llabs (__x); }
   ^
make: *** [release/cafe_commands.o] 错误 1

It likes the problem with C, How can I slove it? Thanks a lot!

**Comment by benfulton** [comment]
I can't read the error messages, but try adding 

#include <cmath>

 to cafe/cafe_commands.cpp .

**Comment by wuxiaopei0509** [comment]
I have resolved it, However another question is the link to tutorial files cannot be available.where can I find them?
Tnanks a lot!
