### ISSUE TITLE
File not found in output by caferror.py

### ISSUE THREAD

**Issue by pnatsi** [hahnlab/CAFE#78]
**Describe the bug**

While trying to run the caferror.py script, I get the error in the screenshot attached
<img width="931" alt="Screenshot 2020-05-25 at 17 49 16" src="https://user-images.githubusercontent.com/19647231/82834302-9d647900-9eb8-11ea-8e40-5e687bfbbd28.png">

 

The command I used to run the script is

python caferror.py -i script.txt -d output -v 0 -f 1

and the script.cafe is attached
[script.txt](https://github.com/hahnlab/CAFE/files/4678362/script.txt)

Any ideas what might be wrong?

Paschalis

**Comment by gwct** [comment]
Hi Paschalis,
This usually means that there was an error running CAFE that prevented the
log file from being created. caferror should have created the caferror.sh
script. Can you run that and see what error it throws? If it didn't create
caferror.sh, just try running the input script you sent and see if it gives
an error.

-Gregg

**Comment by pnatsi** [comment]
Hi Gregg,

The script runs normally when I do `cafe script.cafe`
However, when I do `bash caferror.sh` with the file generated it generates this error:

<img width="1414" alt="Screenshot 2020-05-25 at 19 40 56" src="https://user-images.githubusercontent.com/19647231/82836974-ae64b880-9ebf-11ea-862d-36b67508396c.png">

[caferror.sh.txt](https://github.com/hahnlab/CAFE/files/4678498/caferror.sh.txt)

**Comment by gwct** [comment]
I think that's expected -- bash has no idea how to interpret CAFE's syntax.

Can you try running it like: ./caferror.sh

And tell me if it still completes successfully. That's how caferror tries
to run it.
-Gregg

**Comment by pnatsi** [comment]
It seems to be running ?
Thank you very much

<img width="709" alt="Screenshot 2020-05-25 at 20 18 56" src="https://user-images.githubusercontent.com/19647231/82838782-28e40700-9ec5-11ea-83ed-0064d08844a3.png">

**Comment by gwct** [comment]
Great! Not sure what changed, but glad its running.
Let us know if you run into any more problems.
-Gregg
