### ISSUE TITLE
Error when loading a correct Species tree

### ISSUE THREAD

**Issue by MaximePolicarpo** [hahnlab/CAFE#86]
Hi ! 

I am a french PhD student and I am actually trying to use CAFE to estimate gene gain and loss across my phylogenetic tree but I have a problem when I try to input my tree file : 

cafe
#tree BUSCO_Filtered_Species_Tree_rooted_ultrametric.nwk
Tree must be binary
I get this error message telling me that by tree is not binary while I checked that it was rooted, binary and ultrametric using ape. 

I attached my species tree to this message. Anyone could tell me why do I get this error message (renamed it with a .txt for github) ?
[BUSCO_Filtered_Species_Tree_rooted_ultrametric.nwk.txt](https://github.com/hahnlab/CAFE/files/5523867/BUSCO_Filtered_Species_Tree_rooted_ultrametric.nwk.txt)

(If this can help, I am using Version: 4.2.1, built at Aug 23 2019)

Thanks for any help provided ! 

Maxime Policarpo

**Comment by benfulton** [comment]
Please ask questions about usage here: https://groups.google.com/forum/#!forum/hahnlabcafe

**Comment by MaximePolicarpo** [comment]
Sorry, reposted there !
