### ISSUE TITLE
There is no CAFE report file

### ISSUE THREAD

**Issue by STF003** [hahnlab/CAFE#98]
Hi

I can't run the cafetutorial_report_analysis.py, cause I do not have the report file, the following are my command and result files.

Command
nohup cafe --infile filtered.GeneCounts.tsv --tree r8s.tree.nwk --cores 15 --pvalue 0.05 --output_prefix results &

Result files
Base_asr.tre
Base_change.tab
Base_count.tab
Base_family_results.txt
Base_branch_probabilities.tab
Base_clade_results.txt
Base_family_likelihoods.txt  Base_results.txt

I tried to run it using the test file in the cafe_tutorial and it worked. I noticed that none of my result files had the same format as the tutorial files (ending with .cafe). I ran ‘cafe cafe_shell_scripts/cafetutorial_run7.sh’, but got an error ‘Unrecognized parameter: cafe_shell_scripts/cafetutorial_run7. Sh’. What should I do to get the report file? I would be most grateful if you could give me any help.

**Comment by gwct** [comment]
Hello,
Which version of CAFE are you running? It looks like version 5 based on how
you are running it. If so, then I don't think you need the report_analysis
script anymore. Output summaries should be available in the files it
creates.
The tutorial and all associated files are for CAFE version 4.
-Gregg

**Comment by STF003** [comment]
Hi Gregg,
Thank you for your reply. I want to use CAFE_fig.py to visualize the gene families. But I encountered some troubles, the results of CAFE5 don't contain the input file for CAFE_fig.py. the latter required the cafe format file. I used the report_run1.cafe as input and it worked, but I don't find the same format file in my results.

**Comment by gwct** [comment]
Hey there,
CAFE 5 doesn't produce a report file anymore (as far as I know) so none of the scripts from the CAFE 4 tutorial will be applicable to it's output. It was my understanding that the CAFE 5 output was automatically processed to contain the same information. However, I haven't been heavily involved with the development of CAFE 5 so I can't tell you the specifics of what would match the output of the `CAFE_fig.py` script. Maybe @benfulton could shed some light on this?

I guess my main question at this point for you is: do you want to continue to use CAFE 5 or do you want to go back to CAFE 4 so you can use the associated scripts?

**Comment by benfulton** [comment]
I am not familiar with a CAFE_fig script. Do you mean cafetutorial_draw_tree.py ?

**Comment by aisangekoukou** [comment]
> Hey there, CAFE 5 doesn't produce a report file anymore (as far as I know) so none of the scripts from the CAFE 4 tutorial will be applicable to it's output. It was my understanding that the CAFE 5 output was automatically processed to contain the same information. However, I haven't been heavily involved with the development of CAFE 5 so I can't tell you the specifics of what would match the output of the `CAFE_fig.py` script. Maybe @benfulton could shed some light on this?
> 
> I guess my main question at this point for you is: do you want to continue to use CAFE 5 or do you want to go back to CAFE 4 so you can use the associated scripts?

**Comment by STF003** [comment]
Hey Gregg,

Thanks for your reply, I am trying to solve my problem with other methods.


Tengfei Shen

**Comment by STF003** [comment]
Hi
I used cafetutorial_draw_tree.py but encountered a problem.

Traceback (most recent call last):
  File "/home/data/vip10t43/biosoft/cafe/./cafe_tutorial/python_scripts/cafetutorial_draw_tree.py", line 83, in <module>
    draw_tree(args.input_file, args.tree_type, args.tree, args.id_tree, args.output_file)
  File "/home/data/vip10t43/biosoft/cafe/./cafe_tutorial/python_scripts/cafetutorial_draw_tree.py", line 46, in draw_tree
    labels[row["Node"]] = row
KeyError: 'Node'

The following are my command and input results.
[input.zip](https://github.com/hahnlab/CAFE/files/9015814/input.zip)


python ./cafe_tutorial/python_scripts/cafetutorial_draw_tree.py -i ./results/Base_clade_results.txt -t r8s.tree.modtified.nwk -o out -d '(((((Aoff<42>,Pequ<41>)<46>,((Macu<34>,Egui<33>)<40>,(((Bdis<10>,Osat<9>)<22>,Zmay<21>)<32>,Acom<31>)<39>)<45>)<48>,((((Lchi<20>,Mbio<19>)<30>,(((Ckan<5>,Ccam<4>)<8>)<18>,Csal<17>)<29>)<38>,((Acon<16>,Afim<15>)<28>,Pnig<27>)<37>)<44>,(((Slyc<14>,Dcar<13>)<26>,((((Tcac<1>,Atha<0>)<3>,Ptri<2>)<7>,Rchi<6>)<12>,Vvin<11>)<25>)<36>,(Acoe<24>,Mcor<23>)<35>)<43>)<47>)<50>,Ncol<49>)<52>,Atri<51>)<53>'

**Comment by gwct** [comment]
I've actually never used the cafeetutorial_draw_tree.py command. @benfulton any ideas?

**Comment by benfulton** [comment]
That script does not work with the Base_clade_results.txt file that is created by CAFE 5. I'll see about getting an update for it at some point.

**Comment by STF003** [comment]
I have solved my problem through ggtree, thank you for your attention and the time you put in.

**Comment by gwct** [comment]
Great! If you're willing to share your solution, that might help out others if they have the same issue. No worries if it isn't available though. Thanks!

**Comment by STF003** [comment]
The following is my solution.

##tree file
awk 'NR==3{print}' results/Base_asr.tre | sed 's/.*= //' | sed 's/\*_[0-9]\{1,\}://g' | sed 's/_[0-9]\{1,\}://g' | sed 's/[0-9]\{1,\},/,/g' | sed 's/[0-9]\{1,\})/)/g' | sed 's/>[0-9]\{1,\}\./>/g' | sed 's/_[0-9]\{1,\};/;/' > ./ggtree.input.nwk

##annotation file
sed 's/^\#//' ./results/Base_clade_results.txt > ./Base_clade_results.txt

##vis
library(ggtree)
library(treeio)
library(tidyverse)
library(stringr)

main_tree <- read.newick("ggtree.input.nwk",node.label="support")
family_number_tree <- read.newick("ggtree.input.nwk",node.label="label")
annotation <- read.table("Base_clade_results.txt",header=T,sep="\t",quote="",check.names=F)

species_replace <- annotation[grep(pattern="[a-zA-Z]{4,4}",annotation$Taxon_ID),]
species_replace <- species_replace[,c(1,1)]
species_replace[,2] <- str_replace(species_replace[,2],"<[0-9]{1,2}>","") 
colnames(species_replace) <- c("old name","new name")
main_tree@phylo$tip.label <- species_replace[match(main_tree@phylo$tip.label,species_replace$`old name`),]$`new name`

tip_annotation <- annotation[grep(pattern="[a-zA-Z]{4,4}",annotation$Taxon_ID),]
tip_annotation <- tip_annotation[,c(1,1,2,3)]
tip_annotation[,2] <- str_replace(tip_annotation[,2],"<[0-9]{1,2}>","") 
tip_annotation[,3] <- paste("+ ",tip_annotation[,3],sep="")
tip_annotation[,4] <- paste("- ",tip_annotation[,4],sep="")
tip_annotation$`new name` <- paste(tip_annotation[,2]," ",tip_annotation[,3]," ",tip_annotation[,4],sep="")
tip_annotation <- tip_annotation[,c(1,5)]
colnames(tip_annotation) <- c("old name","new name")
family_number_tree$tip.label <- tip_annotation[match(family_number_tree$tip.label,tip_annotation$`old name`),]$`new name`
family_number_tree$tip.label <- rep("",28)

ggtree(main_tree,layout="rectangular",branch.length="none") +
  geom_tiplab(hjust=-0.05,size=4.5,fontface="italic") +
  xlim(0,12) +
  geom_text(data=family_number_tree,aes(label=label),size=4,hjust=1.05,vjust=-1)

**Comment by benfulton** [comment]
That is very helpful! May we share it with other users who have this problem?
