### ISSUE TITLE
Wrong with cafetutorial_report_analysis.py

### ISSUE THREAD

**Issue by Jenny-chen98** [hahnlab/CAFE#99]
When I ran cafetutorial_report_analysis.py to analyze the CAFE report, I got an indexError. And I don't know what's wrong with my code or data. The whole progress and error information are shown as below:

=======================================================================
                CAFE Report File Analysis
                09.27.2022 | 10:08:27
---------
Parsing format information...

---------
Initializing output structures...

---------
Counting changes per branch...

[********------------------------------------------] 93.75% complete.Traceback (most recent call last):
  File "cafetutorial_report_analysis.py", line 371, in <module>
    results_main, node_fams_main = cra(inlines_main, results_main, node_fams_main, linestart_main, ancfilename, sorted_nodes, 1);
  File "cafetutorial_report_analysis.py", line 151, in cra
    famtree = inline[1];
IndexError: list index out of range

##############################################################################################

I will appreciate if anyone can help me address this bug. THANKS IN ADVANCE

Jessian

**Comment by gwct** [comment]
Hi Jessian,
Just to confirm, you're using CAFE version 4.2.1 or earlier, correct? I know you probably posted here because you are, but since the update to CAFE 5 had some major output format changes some of the scripts don't work for it anymore so I just want to rule that out right away!

Otherwise, I think I would need to see your report file to get an idea for what is happening. Could you copy it here (if it isn't too large)?

**Comment by Jenny-chen98** [comment]
Thank you for your notice, actually when I use the CAFE version 4.2.1 and python 2 environment to get the output file, caretutorial_report_analysis.py can run correctly. I didn't notice the version problem of the software. Thanks again for your help.

Jessian

**Comment by 44314474** [comment]
Hello. I met the same problem. 
But the CAFE version is cafe5, so i did not know how to do.
This is my problem:
 python2 cafe_report_analysis.py -i cafe1/Gamma_report.cafe -o res
=======================================================================
                CAFE Report File Analysis
                01.10.2024 | 08:28:49
---------
Parsing format information...

---------
Initializing output structures...

---------
Counting changes per branch...

[*-------------------------------------------------] 1.671% complete.Traceback (most recent call last):
  File "cafe_report_analysis.py", line 371, in <module>
    results_main, node_fams_main = cra(inlines_main, results_main, node_fams_main, linestart_main, ancfilename, sorted_nodes, 1);
  File "cafe_report_analysis.py", line 254, in cra
    if formatline[j][k] == pairnodeid and float(nodes[j][k]) < 0.01:
IndexError: list index out of range.

And this is my *.cafe file
Tree:(PCHI:437,(PMON:429,(PVAN:404,(PJAP:382,((HAME:256,(PCLA:195,CQUA:195):60):52,(ESIN:186,(COPI:132,PTRI:132):54):122):74):23):25):8):0
Lambda: 0.00153838      
Lambda tree:    (1,(1,(1,(1,((1,(1,1)1)1,(1,(1,1)1)1)1)1)1)1)1
# IDs of nodes:(PCHI<1>,(PMON<2>,(PVAN<3>,(PJAP<4>,((HAME<5>,(PCLA<6>,CQUA<7>)<17>)<16>,(ESIN<8>,(COPI<9>,PTRI<10>)<19>)<18>)<15>)<14>)<13>)<12>)<11>
# Output format for: ' Average Expansion', 'Expansions', 'No Change', 'Contractions', and 'Branch-specific P-values' = (node ID, node ID): (1,12) (2,13) (3,14) (4,15) (16,18) (5,17) (6,7) (8,19) (9,10) 
Average Expansion:      (0.716784,0.00276116)   (0.366774,-0.0537769)   (0.346394,-0.00946683)  (0.651173,-0.802709)    (-0.0318848,-0.115443)  (0.107291,-0.0101243)   (0.142068,-0.0452304)   (0.178686,-0.0390507)   (-0.222602,0.185063)
Expansion :     (4992,12)       (3919,43)       (3879,66)       (4930,210)      (258,372)       (1060,256)      (1063,555)
      (1065,26)       (81,999)
Remain :        (9477,15199)    (8817,14289)    (9118,14924)    (8232,4448)     (14176,13127)   (13154,14495)   (13586,13393)   (13593,14679)   (13335,13900)
Decrease :      (742,0) (2475,879)      (2214,221)      (2049,10553)    (777,1712)      (997,460)       (562,1263)      (553,506)       (1795,312)
'ID'    'Newick'OG0000001       (PCHI_85:437,(PMON_79:429,(PVAN_82:404,(PJAP_88:382,((HAME_71:256,(PCLA_47:195,CQUA_23:195)_38:60)_39:52,(ESIN_39:186,(COPI_14:132,PTRI_23:132)_24:54)_30:122)_36:74)_34:23)_31:25)_22:8)_9:0   0       (PCHI<1>,(PMON<2>,(PVAN<3>,(PJAP<4>,((HAME<5>,(PCLA<6>,CQUA<7>)<17>)<16>,(ESIN<8>,(COPI<9>,PTRI<10>)<19>)<18>)<15>)<14>)<13>)<12>)<11>
OG0000010       (PCHI_76:437,(PMON_19:429,(PVAN_31:404,(PJAP_72:382,((HAME_62:256,(PCLA_17:195,CQUA_11:195)_19:60)_23:52,(ESIN_11:186,(COPI_8:132,PTRI_46:132)_20:54)_19:122)_21:74)_20:23)_18:25)_12:8)_9:0    0       (PCHI<1>,(PMON<2>,(PVAN<3>,(PJAP<4>,((HAME<5>,(PCLA<6>,CQUA<7>)<17>)<16>,(ESIN<8>,(COPI<9>,PTRI<10>)<19>)<18>)<15>)<14>)<13>)<12>)<11>
Thanks in advance!

**Comment by gwct** [comment]
Hi,
The report_analysis script will not work with CAFE5. You'll need to go to the [CAFE5 repo](https://github.com/hahnlab/CAFE5) for support.
